### ISSUE TITLE
disposition Effect-failure to pick new created data-Portfolio Compute function

### ISSUE THREAD

**Issue by DLAtatem** [marcozanotti/dispositionEffect#39]
Hi, I would like to be helped on the following issue- the function Portfolio Compute, is showing me results of the sample code when i have changed the data set , to use my own.  For example, please look at the data  sets-they have my own data eg head(investori) reflects the new data set from head(investor). The same applies for head(marketpricesi) This is done to differentiate from the data set that comes with the code. When i run portfolio compute,  the code returns unchanged data set (the one used by the priducer), even after i change the wording in the portfolio compute function. It appears i have to define the arguments elsewhere, but i am not able to tell where exactly these have to be varied. Will be grateful for your kind feedback

 # portfolio transactions
> head(investori)
# A tibble: 6 x 6
  investor type  asset    quantity price datetime  
     <dbl> <chr> <chr>       <dbl> <dbl> <chr>     
1    10000 B     NBM           100 241   11/11/2014
2    10000 B     STANDARD      100 400.  03/11/2014
3    10001 S     MPICO       99000   6   19/05/2015
4    10002 S     NBS          5489  10   15/03/2012
5    10003 S     FMBCH       21876   6   25/01/2011
6    10003 S     MPICO       45500   2.6 21/07/2010
> #marketprices
> head(marketpricesi)
# A tibble: 6 x 3
  asset datetime price
  <chr> <chr>    <dbl>
1 MPICO 04/01/10   2.6
2 NBM   04/01/10  59  
3 NBS   04/01/10  14  
4 FMBCH 05/01/10  10  
5 ILLOV 05/01/10 110  
6 OML   05/01/10 250  
> # Gains and losses
> portfolio_results <- portfolio_compute(
+   portfolio_transactions = investori, 
+   market_prices = marketpricesi,
+   method = "count"
+ )
Error: Column type of portfolio_transactions should contain 'B' or 'S' only.
> dplyr::select(portfolio_results, -datetime)
  investor asset quantity price RG_count RL_count PG_count PL_count RG_total
1    4273N   ACO      222 2.840        1        0        6        0       45
2    4273N   AST        0 0.000        0        1        0        0        0
3    4273N  IT3S        0 0.000        0        1        0        0        0
4    4273N  LSUG        0 0.000        2        0        4        0      990
5    4273N   TFI     1400 0.284        0        0        0        0        0
  RL_total PG_total PL_total    RG_value    RL_value   PG_value PL_value RG_duration
1        0     1054        0 0.008701958  0.00000000 0.03002533        0     439.900
2      430        0        0 0.000000000 -0.07497820 0.00000000        0       0.000
3      230        0        0 0.000000000 -0.03096539 0.00000000        0       0.000
4        0     1800        0 0.010551792  0.00000000 0.13492566        0    1411.617
5        0        0        0 0.000000000  0.00000000 0.00000000        0       0.000
  RL_duration PG_duration PL_duration
1      0.0000    431.4500           0
2    165.1167      0.0000           0
3     56.9500      0.0000           0
4      0.0000    154.6167           0
5      0.0000      0.0000           0
> # Gains and losses
> portfolio_resultsi <- portfolio_compute(
+   portfolio_transactionsi = investori, 
+   market_pricesi = marketpricesi,
+   method = "count"
+ )
Error in portfolio_compute(portfolio_transactionsi = investori, market_pricesi = marketpricesi,  : 
  unused arguments (portfolio_transactionsi = investori, market_pricesi = marketpricesi)
> dplyr::select(portfolio_resultsi, -datetime)
Error in dplyr::select(portfolio_resultsi, -datetime) : 
  object 'portfolio_resultsi' not found

**Comment by marcozanotti** [comment]
Hi @DLAtatem,
unfortunately without a reprex (reproducible example) it is never possible to help.
Nevertheless, the errors your are encountering are almost self-explanatory:

1.  _"Error: Column type of portfolio_transactions should contain 'B' or 'S' only."_
This error occurs because the type column of portfolio transaction does not contain only B or S.
2. _"Error in portfolio_compute(portfolio_transactionsi = investori, market_pricesi = marketpricesi, :
unused arguments (portfolio_transactionsi = investori, market_pricesi = marketpricesi)"_
This error occurs because you are changing the function arguments' names.

I suggest you to have a look on a tutorial on the usage of functions in R and to revise the data types and structures in R.
Hope you will solve it.

**Comment by DLAtatem** [comment]
Thanks for your kind feedback. While I did not file in a reprex, I thought an explanation of the point i was driving at would suffice, but it has not. Apologies for that. I will endeavor to share a reprex. Now my understanding was and remains that if I change the data set only (assuming the structure and type is in order with the sample data set that you used to come up with the code) then even with the same names with only a change in data set, the code should run properly and derive results. 
So i run your code very well with the data that comes with it. But when I change the data set, even without changing any other code, the errors were the same. That said, I will follow your advice:  take a look at the usage of functions in R and revise my data types and structure. And will surely revert. Many thanks.

**Comment by marcozanotti** [comment]
If you want you can share a slice of your data with me and I can try for you to see whether there is any issue.

**Comment by DLAtatem** [comment]
sure, I can share with you. i guess it will be by email rather than uploading here, please advise

**Comment by marcozanotti** [comment]
yes by email or share it with G Drive

**Comment by DLAtatem** [comment]
Thanks noted. Here is my email address, please drop me a reply so that i can have yours or share by g drive-seems it also needs an email address:

dmphande.dm@gmail.com
