### ISSUE TITLE
significance test of disposition effect

### ISSUE THREAD

**Issue by DLAtatem** [marcozanotti/dispositionEffect#40]
I would like to test the significance of disposition effect from the dataframe of counts of gains and losses. The code below computes disposition effect on each portfolio. The cde is from Cran (developed by Marco Zanotti). It works well. My challenge and where i get errors is testing for statistical significance. I use the data set(DEanalysis -its for 10 investors) that comes with the code.

de <- purrr::map(p_res_full, disposition_compute) %>% 
  dplyr::bind_rows()
skimr::skim(de)
de #  data frame containing DE_count

# test for significance- to find out if the differences (i.e the disposition effected computed by methodology of RG/(RG+PG) - (RL/(RL+PL)) are statistically significant. I test using t test as below:

t.test(de, mu =0, alternative = "greater")

Error in if (stderr < 10 * .Machine$double.eps * abs(mx)) stop("data are essentially constant") : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In mean.default(x) : argument is not numeric or logical: returning NA
2: In var(x) : NAs introduced by coercion

The second part of my challenge is that finance literature about disposition effect computes further the rate at which investors realize gains rather losses. So besides, finding DE as difference, they compute DE as a ratio  of (RG/(RG+PG)) / (RL/(RL+PL)) . Any guidance if there is any code that computes disposition effect in this manner?
Thanks

**Comment by marcozanotti** [comment]
Hi @DLAtatem,
testing significance of disposition effect is not part of the package. It can be done by users applying parametric or non parametric tests as usual with other data in R. Simply use the DE results obtained.

Moreover, we followed exactly the literature definition of disposition effect in our calculations. Please read carefully the documentation of each function and follow the vignettes of the package. Even in the [Getting Started](https://marcozanotti.github.io/dispositionEffect/articles/getting-started.html) page you can find the literature definition of DE.

Before open a new issue, please follow the materials we provide.
Thank you for your interest in the topic.

**Comment by DLAtatem** [comment]
Hi @marcozanotti 
Many thanks for your explanation and guidance to apply parametric and non paramatric tests. The package indeed gives the DE results.
As for literature, i do not dispute what you followed. You cite your methodology from Mazzuchelli et al. But that is not my point. I was checking if testing for signficance is part of the package , which i think you have fully addressed how i can proceed. Am very grateful.

The issue of methodology used to compute disposition effect as the rate at which investors realize gains and losses is from well documented literature on the subject eg Odean 1998, Barber et al 2007, Brown et al 2006, and others. In addition to showing the difference (DE as between -1 to 1), they show a rate. It helps in interpretation and understanding of the bias in my view.
  
Lastly, you say i should follow the material provided before i open an issue. Well, I did (and i will always do), in fact i have read all (not once) and followed through everything the package provides, read all the articles, gone through all the vignettes and i know exactly what this package is doing. I also think i know what it is not doing, hence asking for "signficance test". May be i should not have asked about what the package is not doing or is not expected to do. Am sorry for asking. I will keep learning and will keep reading about the package. Many thanks

**Comment by marcozanotti** [comment]
Hi @DLAtatem,

maybe I did not provide you the right answer. I apologize.
I try to give you a more detailed one now.

I was not saying you should not report the issue, but when you do that keep in mind the following:
- it is written in markdown format, hence follow markdown rules otherwise it will be a mess
- if you provide code, it must be reproducible otherwise it is completely useless and misleading
- usually, an issue is a bug related to the functionalities the package offers
- when the previous is not the case (for instance you want to suggest new features or methodologies the package should include), remember to clearly state that (for instance labelling the issue as enhancement) and to provide full literature of what you would like to have.

Now, let me go through your proposals:

1. we did not include any statistical significance, nor we will do because statistical tests depend on the data you are analysing, not on the DE results themselves.
2. as per the literature, we followed closely Odean and many others. The difference methodology is in fact taken from Odean. He defines the disposition effect as PGR - PLR (proportion of gains/losses realized). This is exactly what we implemented.

Hope this clarifies every point.
Thanks.

**Comment by DLAtatem** [comment]
Hi @marcozanotti 
I think i asked in order to get help and i think you directed me well, thanks. Am not here to pick an argument. Am here to seek help.

What i felt was a wave down or a shut off was your closing remark that i need to check the materials you provided. It was like i did not understand what i wanted or had not gone through it. I felt it was a way of shutting me off or not letting others weigh in on an issue i had raised. Look, you later reflected on it and suggested it as an enhancement. I am not aware of any scientific project that computes DE and comunicate it as merely saying its between -1 and 1. The difference ( DE) in my view needs to be subjected to statistical significance test. We can debate on this one but the point here is that scientific papers go beyond just computing DE. They consider the rate. It does not have to be in the package of course but its an important matter for scientific project. 

I did not propose that you cite Odean. And i will not. Your articles cite the methodology as that of Mazuchelli et al.. a working paper (not sure if its published now). If you ask me, Odean is the one who i find in literature that developed the methodology of PGR-PLR.  Its your preference to cite whoever you wish. 

Thanks for the guidance again and am here to seek help. I think i found it.

Many thanks
