### ISSUE TITLE
Impossibilità riproduzione con diversi dati

### ISSUE THREAD

**Issue by ricnov** [marcozanotti/dispositionEffect#43]
Dopo aver sottomesso alla funzione portfolio_result i dataset investor e marketprices personalmente creati (file .csv), ricevo una serie di warnings relativi all'assenza del prezzo per la specifica transazione anche se presente nel dataset

**Comment by marcozanotti** [comment]
Senza un esempio riproducibile è impossibile fare alcuna valutazione.

Suggerisco di:
- seguire i tutorial del pacchetto
- controllare che i file di input siano precisamente come quelli del tutorial
- warning non sono errori, cercare di capire cosa tali warning comportano

Per poter risolvere il problema è necessario un esempio riproducibile con le info di sistema.

**Comment by ricnov** [comment]
Versione R 4.2.1 in allegato i 2 dataset usati per la funzione portfolio_compute
[marketprices.csv](https://github.com/marcozanotti/dispositionEffect/files/9399724/marketprices.csv)
[investor.csv](https://github.com/marcozanotti/dispositionEffect/files/9399725/investor.csv)

**Comment by marcozanotti** [comment]
Fornire i dati non significa fornire un esempio riproducibile. 
Si vedere il pacchetto reprex (ad esempio) in R per crearne uno.
Le info di sistema non sono la versione di R.

Possono esserci infinite ragioni per le quali su un locale un pacchetto non funziona e senza reproducibilità non è possibile valutare se è un bug oppure un problema dell'utente.

**Comment by ricnov** [comment]
> sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=Italian_Italy.utf8  LC_CTYPE=Italian_Italy.utf8   
[3] LC_MONETARY=Italian_Italy.utf8 LC_NUMERIC=C                  
[5] LC_TIME=Italian_Italy.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dispositionEffect_1.0.1

loaded via a namespace (and not attached):
[1] compiler_4.2.1 magrittr_2.0.3



> library(dispositionEffect)
--------------------------------------------
The dispositionEffect is the first R package to perform behavioural analysis on financial data.
Use citation('dispositionEffect') to cite the package.
Learn more at: https://marcozanotti.github.io/dispositionEffect/index.html
--------------------------------------------
> investor <- read.csv("C:\\Users\\Fmirw\\Desktop\\investor.csv",sep=";")
> marketprices <- read.csv("C:\\Users\\Fmirw\\Desktop\\marketprices.csv",sep=";")
> head(investor)
  investor type asset quantity    price            datetime
1   FBDGSN    B  1730   620130 18.78889 2018-02-07 00:00:00
2   FBDGSN    B  1730   403397 15.27000 2018-10-29 00:00:00
3   FBDGSN    S  1730   679740 15.83462 2018-11-21 00:00:00
4   FBDGSN    S  1730  1548274 15.08200 2019-02-07 00:00:00
5   FBDGSN    B  1730   561026 16.26000 2019-03-05 00:00:00
6   FBDGSN    B  1730   672372 15.55188 2019-04-01 00:00:00
> head(marketprices)
    asset            datetime    price
1 1396214 2019-09-13 00:00:00 13.68750
2 1396214 2019-10-17 00:00:00 14.84107
3 1396214 2019-11-18 00:00:00 14.28813
4 1396214 2020-03-17 00:00:00 10.80760
5 1396214 2020-06-04 00:00:00 10.52375
6 1396214 2020-08-28 00:00:00 11.13500
> portfolio_results <- portfolio_compute(
+     portfolio_transactions = investor, 
+     market_prices = marketprices,
+     method = "count"
+ )
Ci sono 50 o più avvertimenti (utilizza warnings() per visualizzare i primi 50)
> warnings()
Messaggi di avvertimento:
1: Investor FBDGSN, transaction 26, datetime 2018-01-15 00:00:00:
No market prices available for asset(s) 1730

2: Investor FBDGSN, transaction 27, datetime 2018-04-23 00:00:00:
No market prices available for asset(s) 1730

3: Investor FBDGSN, transaction 28, datetime 2018-05-22 00:00:00:
No market prices available for asset(s) 1730

4: Investor FBDGSN, transaction 29, datetime 2018-06-19 00:00:00:
No market prices available for asset(s) 1730

5: Investor FBDGSN, transaction 30, datetime 2018-07-23 00:00:00:
No market prices available for asset(s) 1730

6: Investor FBDGSN, transaction 31, datetime 2018-09-11 00:00:00:
No market prices available for asset(s) 1730

7: Investor FBDGSN, transaction 32, datetime 2019-02-21 00:00:00:
No market prices available for asset(s) 1730

8: Investor FBDGSN, transaction 33, datetime 2019-04-23 00:00:00:
No market prices available for asset(s) 1730

9: Investor FBDGSN, transaction 34, datetime 2019-05-13 00:00:00:
No market prices available for asset(s) 1730

10: Investor FBDGSN, transaction 35, datetime 2019-07-31 00:00:00:
No market prices available for asset(s) 1730

11: Investor FBDGSN, transaction 36, datetime 2019-08-27 00:00:00:
No market prices available for asset(s) 1730

12: Investor FBDGSN, transaction 37, datetime 2019-09-06 00:00:00:
No market prices available for asset(s) 1730

13: Investor FBDGSN, transaction 38, datetime 2019-12-11 00:00:00:
No market prices available for asset(s) 1730

14: Investor FBDGSN, transaction 39, datetime 2020-01-16 00:00:00:
No market prices available for asset(s) 1730

15: Investor FBDGSN, transaction 40, datetime 2020-02-18 00:00:00:
No market prices available for asset(s) 1730

16: Investor FBDGSN, transaction 41, datetime 2020-04-01 00:00:00:
No market prices available for asset(s) 1730

17: Investor FBDGSN, transaction 42, datetime 2020-04-06 00:00:00:
No market prices available for asset(s) 1730

18: Investor FBDGSN, transaction 43, datetime 2020-06-09 00:00:00:
No market prices available for asset(s) 1730

19: Investor FBDGSN, transaction 44, datetime 2020-07-30 00:00:00:
No market prices available for asset(s) 1730

20: Investor FBDGSN, transaction 45, datetime 2020-09-04 00:00:00:
No market prices available for asset(s) 1730

21: Investor FBDGSN, transaction 46, datetime 2020-09-25 00:00:00:
No market prices available for asset(s) 1730

22: Investor FBDGSN, transaction 47, datetime 2020-04-06 00:00:00:
No market prices available for asset(s) 1730

23: Investor FBDGSN, transaction 48, datetime 2020-11-20 00:00:00:
No market prices available for asset(s) 1730, 261579

24: Investor FBDGSN, transaction 49, datetime 2018-01-17 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

25: Investor FBDGSN, transaction 50, datetime 2018-02-07 00:00:00:
No market prices available for asset(s) 261579, 261581

26: Investor FBDGSN, transaction 51, datetime 2018-02-14 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

27: Investor FBDGSN, transaction 52, datetime 2018-03-14 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

28: Investor FBDGSN, transaction 53, datetime 2018-04-13 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

29: Investor FBDGSN, transaction 54, datetime 2018-05-15 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

30: Investor FBDGSN, transaction 55, datetime 2018-07-05 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

31: Investor FBDGSN, transaction 56, datetime 2018-07-31 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

32: Investor FBDGSN, transaction 57, datetime 2018-09-24 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

33: Investor FBDGSN, transaction 58, datetime 2018-10-16 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

34: Investor FBDGSN, transaction 59, datetime 2018-10-30 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

35: Investor FBDGSN, transaction 60, datetime 2018-11-09 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

36: Investor FBDGSN, transaction 61, datetime 2018-12-13 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

37: Investor FBDGSN, transaction 62, datetime 2019-01-31 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

38: Investor FBDGSN, transaction 63, datetime 2019-02-14 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

39: Investor FBDGSN, transaction 64, datetime 2019-03-12 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

40: Investor FBDGSN, transaction 65, datetime 2019-05-03 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581

41: Investor FBDGSN, transaction 66, datetime 2018-02-22 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581, 261591

42: Investor FBDGSN, transaction 67, datetime 2018-04-19 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581, 261591

43: Investor FBDGSN, transaction 68, datetime 2018-05-04 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581, 261591

44: Investor FBDGSN, transaction 69, datetime 2018-10-04 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581, 261591

45: Investor FBDGSN, transaction 70, datetime 2018-10-24 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581, 261591

46: Investor FBDGSN, transaction 71, datetime 2018-11-20 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581, 261591

47: Investor FBDGSN, transaction 72, datetime 2018-11-22 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581, 261591

48: Investor FBDGSN, transaction 73, datetime 2018-12-03 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581, 261591

49: Investor FBDGSN, transaction 74, datetime 2018-12-21 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581, 261591

50: Investor FBDGSN, transaction 75, datetime 2019-02-08 00:00:00:
No market prices available for asset(s) 1730, 261579, 261581, 261591

>

**Comment by marcozanotti** [comment]
Warning legati all'assenza del market price per gli asset specificati.
Non sono errori, ma segnalazioni che manca quel market price nel dataset dei prezzi di mercato.

Nessun bug / errore. Chiudo la issue.

**Comment by ricnov** [comment]
Purtroppo i market prices sono tutti presenti forse, mi chiedevo, ma non trovo un riferimento nella documentazione se il formato ISO del campo datetime sia corretto

**Comment by marcozanotti** [comment]
Il formato è standard, YYYY-mm-dd HH:MM:SS

**Comment by ricnov** [comment]
Anche importando i dati utilizzando la classe POSIXct (la stessa del dataframe originale), ricevo gli stessi warning.

**Comment by marcozanotti** [comment]
Controllerò gli warning però ripeto, non sono errori.

**Comment by marcozanotti** [comment]
@ricnov ho provveduto a verificare.
Di seguito l'esempio:

```
library(tidyverse)
library(dispositionEffect)

inv <- readr::read_csv2("investor.csv")
mrkt <- readr::read_csv2("marketprices.csv")

res <- portfolio_compute(portfolio_transactions = inv, market_prices = mrkt)
warnings()
```
Primo messaggio di errore:

```
Warning messages:
	1: Investor FBDGSN, transaction 26, datetime 2018-01-15:
	No market prices available for asset(s) 1730
```

Come si evince dal messaggio ben chiaro non è presente tra i market prices un valore per l'asset 1730.
Per controllare, verifico che valori ci sono alla data 2018-01-15.

`mrkt %>% dplyr::filter(datetime == lubridate::ymd("2018-01-15"))`

Il risultato è il seguente:

![image](https://user-images.githubusercontent.com/26893569/189325579-90c48905-6f63-4738-9195-7c539d65cd2c.png)

Quindi esattamente quanto segnalato dal warning.
Tutti gli altri warning segnalano lo stesso problema.

Ti suggerisco di studiare meglio il funzionamento del pacchetto `dispositionEffect` e della funzione `portfolio_compute`.
Tra gli argomenti della funzione, infatti, esiste il parametro `exact_market_price`, specificato come segue nell'help:

_Logical. If TRUE then closest_market_price uses exact datetime match to look for the closest price of each asset. It usually speeds up computation by a small degree, but it requires the market_prices to have the prices for each transaction asset along each transaction datetimes._

Nessun bug. Sbagliato utilizzo utente.

**Comment by ricnov** [comment]
Nessuna transaction è prevista per la data segnalata per lo specifico asset

**Comment by marcozanotti** [comment]
Quello è un problema del dataset che stai usando.

**Comment by ricnov** [comment]
Sì chiaro, grazie per il supporto!
